# Generated by Django 3.2.9 on 2022-04-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskilla', '0002_auto_20211101_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения задачи'),
        ),
    ]
